Resources:
  MyDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS DB instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0

  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: mysql
      EngineVersion: '8.0'
      PubliclyAccessible: True
      MasterUsername: '{{resolve:secretsmanager:mysql:SecretString:username}}'  # Referencing the username stored in Secrets Manager
      MasterUserPassword: '{{resolve:secretsmanager:mysql:SecretString:password}}'  # Referencing the password stored in Secrets Manager
      DBName: practice
      VPCSecurityGroups:
        - !GetAtt MyDBSecurityGroup.GroupId  # Reference the security group ID
      BackupRetentionPeriod: 0  # Disable automated backups

  MyDBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: mysql  # Set the secret name to 'mysql'
      Description: Secret for storing DB credentials
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'  # Set default username
        GenerateStringKey: "password"
        PasswordLength: 12  # Set password length
        ExcludePunctuation: true  # Exclude special characters in password generation
      Tags:
        - Key: Name
          Value: mysql

  MyDBSecretTarget:
    Type: "AWS::SecretsManager::SecretTargetAttachment"
    Properties:
      SecretId: !Ref MyDBSecret
      TargetId: !Ref MyDBInstance
      TargetType: AWS::RDS::DBInstance

Parameters:
  Region:
    Type: String
    Default: "us-east-1"
    AllowedValues: 
      - "us-east-1"
      - "us-west-1"
      - "us-west-2"
      - "eu-west-1"
    Description: "Select the region to deploy the resources."
